[package]
name = "green/roblox-projects"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Replica = "aykut92/replica@0.1.7"
Promise = "evaera/promise@4.0.0"
FormatNumber = "kumarion/formatnumber@0.0.1"

[server-dependencies]
ProfileStore = "lm-loleris/profilestore@1.0.3"